### PR TITLE
Very naive / simple API Token login implementation

### PR DESCRIPTION
**Pull request by naerymdan**
Would help with #63 and #69 since it'd at least allow using a API token instead of a password.

Warning: I did not even compile these changes, even less tried them out.

### CODE REVIEW

**Comment by phantomate** [comment]
Hi, I appreciate your work but unfortunately this won't work. I try to implement it in the next release

**Comment by naerymdan** [comment]
Doesn't `final UserToken userToken = await apiUser.createAuthToken(event.username, event.password);` gives you a token similar to the one we can create for API in Settings -> API?

**Comment by phantomate** [comment]
Yeah thats right

**Comment by naerymdan** [comment]
I cloned the repo and compiled/ran it on Android Studio on an emulator. The API token from the UI works fine in the password bypass I quickly hacked together in this PR.

For reference I made said token with "write read bookmarklet" (with spaces between the scopes)

Screenshot 2024-05-13 205045

I do have a some weird behaviors with the Hive.box where it starts returning null after returning valid data a few times, but I assume this is some mismatch of Flutter/Dart/Android version with how I'm compiling it.

**Pull request closed without merging**
